/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import operations.Lecturer;
import operations.Student;

/**
 *
 * @author Dinet
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roleCmBx = new javax.swing.JComboBox<>();
        nameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt1 = new javax.swing.JPasswordField();
        passwordTxt2 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText(" Role");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel7.setText("Password");

        roleCmBx.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        roleCmBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select your role>", "Student", "Lecturer" }));
        roleCmBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleCmBxActionPerformed(evt);
            }
        });

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(204, 204, 204));
        nameTxt.setText("Enter your Name");
        nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTxtMouseClicked(evt);
            }
        });
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTxtKeyPressed(evt);
            }
        });

        ageTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ageTxt.setForeground(new java.awt.Color(204, 204, 204));
        ageTxt.setText("Enter your Age");
        ageTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ageTxtMouseClicked(evt);
            }
        });
        ageTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTxtKeyPressed(evt);
            }
        });

        usernameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(204, 204, 204));
        usernameTxt.setText("Enter your Username");
        usernameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTxtMouseClicked(evt);
            }
        });
        usernameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameTxtKeyPressed(evt);
            }
        });

        passwordTxt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordTxt1.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt1.setText("Password1");
        passwordTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTxt1MouseClicked(evt);
            }
        });
        passwordTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxt1KeyPressed(evt);
            }
        });

        passwordTxt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordTxt2.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt2.setText("Password2");
        passwordTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTxt2MouseClicked(evt);
            }
        });
        passwordTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxt2KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Already a Member? Sign in Here");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jButton1.setText("Sign up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/Images/Webp.net-resizeimage (1).png"))); // NOI18N
        jLabel1.setText("Registration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(16, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(jLabel2)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(passwordTxt1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(roleCmBx, javax.swing.GroupLayout.Alignment.LEADING, 0, 293, Short.MAX_VALUE)
                                        .addComponent(passwordTxt2))
                                .addContainerGap(58, Short.MAX_VALUE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(roleCmBx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(passwordTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(passwordTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>

    private void roleCmBxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setLocationRelativeTo(null);
        String role=roleCmBx.getSelectedItem().toString();
        if (nameTxt.getText().isEmpty() == true || ageTxt.getText().isEmpty() == true || usernameTxt.getText().isEmpty() == true || passwordTxt1.getText().isEmpty() == true || passwordTxt2.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null, "Please Fill all Fields!");
        }
        else if(nameTxt.getText().equals("Enter your Name")|| ageTxt.getText().equals("Enter your Age")|| usernameTxt.getText().equals("Enter your Username") || passwordTxt1.getText().equals("Password1")|| passwordTxt2.getText().equals("Password2")){
            JOptionPane.showMessageDialog(null, "Don't leave default values");
        }
        else {

            if(role.equals("Student")){
                if (passwordTxt1.getText().equals(passwordTxt2.getText())) {
                    int response=JOptionPane.showConfirmDialog(null,"Cofirm your personal details and process to subject enrollment");
                    if(response==JOptionPane.YES_OPTION){
                        try {
                            Student student = new Student();
                            student.setName(nameTxt.getText());
                            student.setAge(Integer.parseInt(ageTxt.getText()));
                            student.setUser_name(usernameTxt.getText());
                            student.setPassword(passwordTxt1.getText());
                            student.AddPersonData(student.role1, student.role2);



                        }
                        catch (SQLIntegrityConstraintViolationException ex) {

                            JOptionPane.showConfirmDialog(null,"Username is Already Exist!","Duplicate value",JOptionPane.ERROR_MESSAGE);

                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        catch (NumberFormatException ne) {
                            JOptionPane.showMessageDialog(null,"Age Should be a Numeric Value","Invalid Input",JOptionPane.ERROR_MESSAGE);
                        } catch (SQLException ex) {
                            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }


                } else {
                    JOptionPane.showMessageDialog(null, "Passwords do not match!");
                }
            }
            else if(role.equals("Lecturer")){
                if (passwordTxt1.getText().equals(passwordTxt2.getText())) {
                    int response=JOptionPane.showConfirmDialog(null,"Cofirm your personal details and process to subject enrollment");
                    if(response==JOptionPane.YES_OPTION){
                        try {
                            Lecturer lecturer = new Lecturer();
                            lecturer.setName(nameTxt.getText());
                            lecturer.setAge(Integer.parseInt(ageTxt.getText()));
                            lecturer.setUser_name(usernameTxt.getText());
                            lecturer.setPassword(passwordTxt1.getText());
                            lecturer.AddPersonData(lecturer.role1, lecturer.role2);
                            this.dispose();
                            new Home().setVisible(true);


                        } catch (SQLIntegrityConstraintViolationException ex) {

                            JOptionPane.showConfirmDialog(null,"Username is Already Exist!","Duplicate value",JOptionPane.ERROR_MESSAGE);

                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        catch (NumberFormatException ne) {
                            JOptionPane.showMessageDialog(null,"Age Should be a Numeric Value","Invalid Input",JOptionPane.ERROR_MESSAGE);
                        } catch (SQLException ex) {
                            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
                else {
                    JOptionPane.showMessageDialog(null, "Passwords do not match!");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please Select a Valid Role");
            }
        }


    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        System.exit(0);
    }

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {

        this.dispose();
        Home home=new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null);

    }

    private void nameTxtMouseClicked(java.awt.event.MouseEvent evt) {
        if(nameTxt.getText().equals("Enter your Name")){
            nameTxt.setText(null);
            nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14));
            nameTxt.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void ageTxtMouseClicked(java.awt.event.MouseEvent evt) {
        if(ageTxt.getText().equals("Enter your Age")){
            ageTxt.setText(null);
            ageTxt.setFont(new java.awt.Font("Tahoma", 0, 14));
            ageTxt.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void usernameTxtMouseClicked(java.awt.event.MouseEvent evt) {
        if(usernameTxt.getText().equals("Enter your Username")){
            usernameTxt.setText(null);
            usernameTxt.setFont(new java.awt.Font("Tahoma", 0, 14));
            usernameTxt.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void passwordTxt1MouseClicked(java.awt.event.MouseEvent evt) {

        if(passwordTxt1.getText().equals("Password1")){
            passwordTxt1.setText(null);
            passwordTxt1.setFont(new java.awt.Font("Tahoma", 0, 14));
            passwordTxt1.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void passwordTxt2MouseClicked(java.awt.event.MouseEvent evt) {

        if(passwordTxt2.getText().equals("Password2")){
            passwordTxt2.setText(null);
            passwordTxt2.setFont(new java.awt.Font("Tahoma", 0, 14));
            passwordTxt2.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        Home home=new Home();
        home.setVisible(true);
    }

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {
        jLabel8.setForeground(Color.BLACK);
    }

    private void nameTxtKeyPressed(java.awt.event.KeyEvent evt) {
        if(nameTxt.getText().equals("Enter your Name")){
            nameTxt.setText(null);
            nameTxt.setFont(new java.awt.Font("Tahoma", 0, 14));
            nameTxt.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void ageTxtKeyPressed(java.awt.event.KeyEvent evt) {
        if(ageTxt.getText().equals("Enter your Age")){
            ageTxt.setText(null);
            ageTxt.setFont(new java.awt.Font("Tahoma", 0, 14));
            ageTxt.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void usernameTxtKeyPressed(java.awt.event.KeyEvent evt) {
        if(usernameTxt.getText().equals("Enter your Username")){
            usernameTxt.setText(null);
            usernameTxt.setFont(new java.awt.Font("Tahoma", 0, 14));
            usernameTxt.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void passwordTxt1KeyPressed(java.awt.event.KeyEvent evt) {
        if(passwordTxt1.getText().equals("Password1")){
            passwordTxt1.setText(null);
            passwordTxt1.setFont(new java.awt.Font("Tahoma", 0, 14));
            passwordTxt1.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    private void passwordTxt2KeyPressed(java.awt.event.KeyEvent evt) {
        if(passwordTxt1.getText().equals("Password1")){
            passwordTxt1.setText(null);
            passwordTxt1.setFont(new java.awt.Font("Tahoma", 0, 14));
            passwordTxt1.setForeground(new java.awt.Color(51, 51, 51));
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt1;
    private javax.swing.JPasswordField passwordTxt2;
    private javax.swing.JComboBox<String> roleCmBx;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration
}
